
* 0826

「 7: 《菜根谭》，取自宋儒汪革语:「人就咬得菜根，则百事可成。」意思是说，一个人只要就够坚强地适应清贫的生活，不论做什么事情，都会有所成就。明于孔兼在为《菜根谭》写的(题词)中，进一步阐述道:「『谭』」以『根谭』名，固自清苦历练中来，亦自栽培灌溉里得，其颠顿风波、备尝险阻可想矣。」又引用洪应明的话说:「天劳我以形，吾逸吾心以补之;天阨我以遇，吾亨吾道以通之。」于氏的解释，增加了这样一层含意，即一个人面对厄运，必须坚定自己的操守，奋发努力，辛勤培植与浇灌自己的理想。乾隆间署名三山病夫通理的(重刊菜根谭序)则说:「凡种菜者，必要厚培其根，其味乃厚。」并引月古语「性定菜根香」，说明只有心性澹泊沉静的人，才能领会其中的旨意。
搬运工伴着台风来了
我在办公室坐等台风 」
- - - - - - - - - - - - - - -
老师，我写了一篇”为什么种菜可以消除焦虑、抑郁、失眠“的文章，可以分享过来吗？


** 潘鹰老师

下午有点时间，和各位再分享一段《王阳明全集》之静心录的文章[抱拳]

答徐成之（1）
辛未
  汝华（2）相见于逆旅，闻成之启居甚悉；然无因一面，徒增悒怏。吾乡学者几人，求其笃信好学如吾成之者谁欤？求其喜闻过，忠告善道如吾成之者谁欤？过而莫吾告也，学而莫吾与也，非吾成之思而谁思欤？嗟吾成之，幸自爱重！

注释：（1）徐守诚：万历《绍兴府志》：字成之，余姚人。弘治进士，授南兵部主事
（2）汝华：郑岳（１４６８—１５３９，字汝华，号山斋，弘治六年进士，福建莆田人，与阳明关系甚笃，《明史•列传第九十一》）有事迹记载。

译文：与汝华在旅途相遇，通过他对您的生活起居有了相当多的了解；然而却无缘相见，徒增了不少遗憾。我们乡党之中的学者中，真正像您一样笃信好学又有谁呢？像您一样追求“闻过则喜，”“忠告善道”的又有谁呢？有过无人告知，学习无人鼓励，这个时候不想念您又想念谁呢？唉，成之兄，一定要好好保重啊！

自人之失其所好，仁之难成也久矣。向吾成之在乡党中，刻厉自立，众皆非笑，以为迂腐，成之不为少变。仆时虽稍知爱敬，不从众非笑，然尚未知成之之难得如此也。今知成之之难得，则又不获夕相与，岂非大可憾欤！

自从人们失去了对道义的喜好，仁德之风难以达成已经很久了。以往您在乡党之中，对自己的要求苛刻严厉，志向坚定，旁人都以为迂腐，所以非议讥笑，而您不为所动。我当时虽然稍稍存了一点敬爱，不附从他人，然而尚未了解您当时有多么难。如今知道了，却又没有机会朝夕相处，岂非太遗憾了！

修己治人，本无二道。政事虽剧，亦皆学问之地，谅吾成之随在有得。然何从一闻至论，以洗凡近之见乎！爱莫为助。近为成之思进学之功，微觉过苦。先儒所谓志道恳切，固是诚意；然急迫求之，则反为私己，不可不察也。日用间何莫非天理流行，但此心常存而不放，则义理自熟。

修养自己，治理民众，本来没有什么区别。政事虽烦剧，也都是可以增进学问的地方，您应该已经伴随着政事的处理，个人修养也有所得。然而何必一定要刚听到至深的道理，马上就期望改变自己以前的所有见解呢？唉，我虽然也知道这一点，但是也没办法帮到您啊，今日想起您的求学上进所用的工夫，微微觉得有些太苦了。先辈儒家所谓“志道恳切”，当然是需要诚意，然而若急迫追求，则反为私欲了，这一点不可不察啊。在我们日常生活中莫不有天理流行作用，只要常常存着这颗天理之心不放失，则学问道理自然精熟。

孟子所谓“勿忘勿助。深造自得”者矣。学问之功何可缓，但恐着意把持振作，纵复有得，居之恐不能安耳。成之之学，想亦正不如此。以仆所见，微觉其有近似者，是以不敢不尽。亦以成之平时之乐闻，且欲以是求教也。

孟子所谓“不要遗忘而间断，不要急功近利而揠苗助长，而是要深入揣摩玩味，以达到精深的境地”。求学用功当然不能缓，但就怕刻意地让自己振作不松懈，纵然有所收获，面对这种结果恐怕也不能愉悦而心安。您在求学方面，想必也不会如此。以我之见，微微觉得有些类似，所以不敢不全部提出来。也是因为您平时愿意听不同意见，所以我才阐发上述观点，以便听听您的意见。

各位师友，学道是一件苦差事否？

* 0827

肤白

貌美

大象腿

健忘

爱食堂

武功高强, 以为老公金刚狼

无心计

性冷清

爱借书(注意不是看书)

吵架不服输

附送一个优点:
女性造福者: 每到一处, 该地方的男子都醒悟: 原来我家娘子脾气好到让我吐


** 七兄

从没去见过老爸和老妈发火，倒是老妈有时哭哭啼啼的闹事
我刚结婚时夫人武功高强，经常拿我练手助我修炼铁布衫
我最初从不还手
夫人高六时会把我打倒在地
脸上胳膊上有时留下九爱白骨抓痕，我心里暗存侥幸，因为我有一好哥们脸上经常挂彩，常常向我哭诉
我只是皮外小伤，毛毛雨
后来剪刀事件爬楼见上文
话说有一次夫人向我发动袭击
我无心开启两国大战
说时迟
脚已自然飞起，夫人飞了出去
我惊呆害怕极了…
我是真心无意冒犯夫人，更不会想到自己会心狠脚辣如此，完全本能正当防卫

（我祖籍河北沧州，父亲习武不曾传我，怕惹祸，因我一表叔失手弄出了人命）
* 0904 武则天的好色和她的<<金刚经>>开经偈

龙思:
@潘老师好，武则天为什么那么多男宠，这个是有违佛法的

Qian:
说明武则天已经不着相了[微笑]

ruifeng:
在帝王眼中，其他包括佛都是枝枝叶叶。属于另外的体系。

三宫六院七十二妃才是根本的体现。

星星:
武则天也着相的，只是心已经很大了。

武则天为什么那么多男宠，这个是有违佛法的
也许是你没懂佛法吧。

佛法根本不讲事相，只讲那个根本空相，人心只有去相放下，才会大得很。

花开:
我觉得也是

jinxia:
那个时候女皇有男宠，也是不逾矩吧

qian:
问题是这句话为什么会问出来？对佛法怀疑还是对人质疑？
一个人要问，内心一定有个执着在那里

龙思:
武则天有能力有很多男宠，却选择忠于一人，那才是不着相。 有很多男人或女人，谁有权力了谁不会啊，好色都成“不着相”了？

武则天那么多男宠，那么她是不是允许男宠也有很多女人呢？
如果不允许，她岂不是连“己所不欲勿施于人”都没做到？

雪儿:
@龙思  您说的也有道理。历史上，武则天是个很有争议的人物。一般来说，封建社会的帝皇，是会利用军队、宗教等工具的，来巩固她的政权的。同时，从武则天所作的开经偈中，我觉得她甚通佛理的。作为千古一女皇，这也是她宿世的业力。至于她养男宠，个人认为她既然已成了君王，当然也可以享受男性帝皇一样的特权。

龙思:
享受是可以享受，只是说这个不算什么圣人之学，只是普罗大众的欲望罢了
对了，"无上甚深微妙法,百千万劫难遭遇，吾今见闻得受持，愿解如来真实义"那几句，确实是武则天说的？ 不是金刚经原来有的？

雪儿:
@龙思 这首开经偈，确实是武则天写的！

龙思:
[赞]
那是慧根不浅

jinhua:
可能很多人也会认为这偈不是她写的呢，毕竟历史是当权者写的[调皮]

龙思:
不知道会不会是其他高人写的，献给武则天？

雪儿:
@jinhua@龙思  赞叹二位的独立思考，即穿透了表象去探索背后的真相，同时，也有善用妙用。将你们的灵活方便吸入中心。[玫瑰][玫瑰][强][强]🙏🙏

--------
从武则天的所作所为看，那么多男宠，显然是异常的。
如果她允许那些男宠，也可以有很多女人，那她就是做到了"不着相"，是真悟了佛法。
否则，很大嫌疑只是利用了佛法，未能觉悟。
* 0908

龙思:
脱三界，了生死。老师们理解的三界是？



同心圆:
@龙思 有界，无界，无无界。


「 雪儿惜时🌻: @龙思  三界是指欲界，色界，无色界。 」
- - - - - - - - - - - - - - -
我之前没查这个，自己想到的是人界，鬼界，神界。


生而为人，入地狱为鬼，出地狱为神，比如佛陀


「 同心圆: @龙思 有界，无界，无无界。 」
- - - - - - - - - - - - - - -
@同心圆 ，这3界具体怎么理解？

同心圆:
人鬼神，都是有界。
人者，仁也。鬼者，归也，神者，伸也。仁者，道也，鬼神者，道之痕也。

jinxia:
@龙思 老师指的是了脱生死的十法界吧
三恶界：地狱、饿鬼、畜牲
三善界：阿修罗、人、天神
四圣界：阿罗汉、辟支佛、菩萨、佛
龙思老师想以后去哪界啊🙏🙏

同心圆:
心外无界，界都在心内。


合一:
「同心圆：
心外无界，界都在心内。」
- - - - - - - - - - - - - - -
内外一立，心即是界。

界显必限，界限分明，必坠三界。

不分界限，三界难言，若言三界，必立内外。

龙思:
👍，心无挂碍，就是出了三界?

雪儿:
@合一  佛说三界（欲界、色界、无色界），与您表达的其实维度不一样的。

“跳出三界，不在五行中。”那是已经成佛成圣了！[太阳]🙏

合一:
可以一样，亦可异样，一样与否，因界而限。

雪儿:
如：分别一切法，不起分别想。能善分别诸法相，于第一义而不动。

龙思问的是哪三界，那就是说我们回答就是哪个三界好嘞，至于跳出了三界，不在五行中，那肯定是成佛成圣了，真正的圣贤，那是跳出了三界，不在五行中，接下来是这样子的。
