
* 0826

「 7: 《菜根谭》，取自宋儒汪革语:「人就咬得菜根，则百事可成。」意思是说，一个人只要就够坚强地适应清贫的生活，不论做什么事情，都会有所成就。明于孔兼在为《菜根谭》写的(题词)中，进一步阐述道:「『谭』」以『根谭』名，固自清苦历练中来，亦自栽培灌溉里得，其颠顿风波、备尝险阻可想矣。」又引用洪应明的话说:「天劳我以形，吾逸吾心以补之;天阨我以遇，吾亨吾道以通之。」于氏的解释，增加了这样一层含意，即一个人面对厄运，必须坚定自己的操守，奋发努力，辛勤培植与浇灌自己的理想。乾隆间署名三山病夫通理的(重刊菜根谭序)则说:「凡种菜者，必要厚培其根，其味乃厚。」并引月古语「性定菜根香」，说明只有心性澹泊沉静的人，才能领会其中的旨意。
搬运工伴着台风来了
我在办公室坐等台风 」
- - - - - - - - - - - - - - -
老师，我写了一篇”为什么种菜可以消除焦虑、抑郁、失眠“的文章，可以分享过来吗？


** 潘鹰老师

下午有点时间，和各位再分享一段《王阳明全集》之静心录的文章[抱拳]

答徐成之（1）
辛未
  汝华（2）相见于逆旅，闻成之启居甚悉；然无因一面，徒增悒怏。吾乡学者几人，求其笃信好学如吾成之者谁欤？求其喜闻过，忠告善道如吾成之者谁欤？过而莫吾告也，学而莫吾与也，非吾成之思而谁思欤？嗟吾成之，幸自爱重！

注释：（1）徐守诚：万历《绍兴府志》：字成之，余姚人。弘治进士，授南兵部主事
（2）汝华：郑岳（１４６８—１５３９，字汝华，号山斋，弘治六年进士，福建莆田人，与阳明关系甚笃，《明史•列传第九十一》）有事迹记载。

译文：与汝华在旅途相遇，通过他对您的生活起居有了相当多的了解；然而却无缘相见，徒增了不少遗憾。我们乡党之中的学者中，真正像您一样笃信好学又有谁呢？像您一样追求“闻过则喜，”“忠告善道”的又有谁呢？有过无人告知，学习无人鼓励，这个时候不想念您又想念谁呢？唉，成之兄，一定要好好保重啊！

自人之失其所好，仁之难成也久矣。向吾成之在乡党中，刻厉自立，众皆非笑，以为迂腐，成之不为少变。仆时虽稍知爱敬，不从众非笑，然尚未知成之之难得如此也。今知成之之难得，则又不获夕相与，岂非大可憾欤！

自从人们失去了对道义的喜好，仁德之风难以达成已经很久了。以往您在乡党之中，对自己的要求苛刻严厉，志向坚定，旁人都以为迂腐，所以非议讥笑，而您不为所动。我当时虽然稍稍存了一点敬爱，不附从他人，然而尚未了解您当时有多么难。如今知道了，却又没有机会朝夕相处，岂非太遗憾了！

修己治人，本无二道。政事虽剧，亦皆学问之地，谅吾成之随在有得。然何从一闻至论，以洗凡近之见乎！爱莫为助。近为成之思进学之功，微觉过苦。先儒所谓志道恳切，固是诚意；然急迫求之，则反为私己，不可不察也。日用间何莫非天理流行，但此心常存而不放，则义理自熟。

修养自己，治理民众，本来没有什么区别。政事虽烦剧，也都是可以增进学问的地方，您应该已经伴随着政事的处理，个人修养也有所得。然而何必一定要刚听到至深的道理，马上就期望改变自己以前的所有见解呢？唉，我虽然也知道这一点，但是也没办法帮到您啊，今日想起您的求学上进所用的工夫，微微觉得有些太苦了。先辈儒家所谓“志道恳切”，当然是需要诚意，然而若急迫追求，则反为私欲了，这一点不可不察啊。在我们日常生活中莫不有天理流行作用，只要常常存着这颗天理之心不放失，则学问道理自然精熟。

孟子所谓“勿忘勿助。深造自得”者矣。学问之功何可缓，但恐着意把持振作，纵复有得，居之恐不能安耳。成之之学，想亦正不如此。以仆所见，微觉其有近似者，是以不敢不尽。亦以成之平时之乐闻，且欲以是求教也。

孟子所谓“不要遗忘而间断，不要急功近利而揠苗助长，而是要深入揣摩玩味，以达到精深的境地”。求学用功当然不能缓，但就怕刻意地让自己振作不松懈，纵然有所收获，面对这种结果恐怕也不能愉悦而心安。您在求学方面，想必也不会如此。以我之见，微微觉得有些类似，所以不敢不全部提出来。也是因为您平时愿意听不同意见，所以我才阐发上述观点，以便听听您的意见。

各位师友，学道是一件苦差事否？

* 0827

肤白

貌美

大象腿

健忘

爱食堂

武功高强, 以为老公金刚狼

无心计

性冷清

爱借书(注意不是看书)

吵架不服输

附送一个优点:
女性造福者: 每到一处, 该地方的男子都醒悟: 原来我家娘子脾气好到我满足
